python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_DataB -es=0 -ues=0 -res=0 -jes=0 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_DataC -es=0 -ues=0 -res=0 -jes=0 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_DataA -es=0 -ues=0 -res=0 -jes=0 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_DataD -es=0 -ues=0 -res=0 -jes=0 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_TTToHadronic -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_TTToSemiLeptonic -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_TTTo2L2Nu -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_DYlow -es=1 -ues=0 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_DY_v1 -es=1 -ues=0 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_DY1_v1 -es=1 -ues=0 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_DY1_v2 -es=1 -ues=0 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_DY2_v1 -es=1 -ues=0 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_DY2_v2 -es=1 -ues=0 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_DY3_v1 -es=1 -ues=0 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_DY3_v2 -es=1 -ues=0 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_DY4_v1 -es=1 -ues=0 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_EWKZNuNu -es=1 -ues=0 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_EWKZLL -es=1 -ues=0 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_ZHTT -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_EWKWplus -es=0 -ues=0 -res=0 -jes=0 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_EWKWminus -es=0 -ues=0 -res=0 -jes=0 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_WplusHTT -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_VBFHTT -es=1 -ues=0 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_W_v1 -es=0 -ues=0 -res=0 -jes=0 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_W1_v1 -es=0 -ues=0 -res=0 -jes=0 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_W2_v1 -es=0 -ues=0 -res=0 -jes=0 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_W2_v2 -es=0 -ues=0 -res=0 -jes=0 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_W3_v1 -es=0 -ues=0 -res=0 -jes=0 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_W3_v2 -es=0 -ues=0 -res=0 -jes=0 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_W4_v1 -es=0 -ues=0 -res=0 -jes=0 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_W4_v2 -es=0 -ues=0 -res=0 -jes=0 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_ST_tW_top -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_ST_t_top -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_ST_t_antitop -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_ST_tW_antitop -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_GGHTT -es=1 -ues=0 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_WminusHTT -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_WW_v1 -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_WW_v2 -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_WZ_v1 -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_WZ_v2 -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_ZZ_v1 -es=1 -ues=1 -res=0 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_VBFHWW -es=1 -ues=0 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_GGZHWW -es=1 -ues=1 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_WplusHWW -es=1 -ues=1 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_WminusHWW -es=1 -ues=1 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_ZHWW -es=1 -ues=1 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_WG -es=1 -ues=1 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_GGHWW -es=1 -ues=1 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_GGZHLLTT -es=1 -ues=1 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_GGZHQQTT -es=1 -ues=1 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_GGZHNNTT -es=1 -ues=1 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
python svFitSubmitter.py -sd /hdfs/store/user/caillol/smhmt2018_4aug_merged/Out_ttHTT -es=1 -ues=1 -res=1 -jes=1 --jobName smhmt2018_svfitted_4aug
